steps:
  # Deploy all Firebase services (Firestore rules/indexes, Functions, and Hosting)
  - name: 'us-docker.pkg.dev/firebase-cli/us/firebase'
    args:
      - 'deploy'
      - '--project=respondentpro-xyz'
      - '--non-interactive'
      - '--token=${_FIREBASE_TOKEN}'

# Substitution variables
# _FIREBASE_TOKEN should be set as a substitution variable in Cloud Build
# You can get this token by running: firebase login:ci
substitutions:
  _FIREBASE_TOKEN: ''

# Build timeout (optional, adjust as needed)
timeout: '1200s'

# Build options - required when service_account is specified
options:
  logging: CLOUD_LOGGING_ONLY
